### ISSUE TITLE
Listing all functional requirements of Our Web Browser 

### ISSUE THREAD

**Issue by khaledabdelfatah** [khaledabdelfatah/Web-Browser-Using-JavaFX-Project#1]
We Had To List Our Web Browser Requirements That Our System Had To Do ☺

**Comment by mahmoud-said-ramadan** [comment]
-The user choose between if he wants the search prosse wil be saved or not
-the user determines an email to save his search prosses and his short cuts
--Make more than one model to allow the user to choos from them

**Comment by AhmedMostafaElsisy** [comment]
1. add a ready made shortcut for  the most Famous wed site
2. build in apps for blocking Advertisement
3. Dark mode

**Comment by khaledabdelfatah** [comment]
•Make The The Web Safe For Eyes By Choosing Colors That isn't Harmful For Eyes
•Make A Simple Gui That The User Can Interact With
•Make the User choose His Most Visited Web Site and Make Access to Them More Easier
•Make All Searched  Data Organized in a way that View the most matching First 
•We Can Cheek if the URL That The User put if start with https that is SAFE ,else we display A warring message  to tell the User That this Site NOT SAFE
•View Image and Video Easily
•Try To Make a Specific page to be ridden offline(downlod it or take a screen shot of it) 
•Make User able to refresh page
•Make user able to open multiple tabs

**Comment by eslam5elesawy** [comment]
bookmarks and themes linked by user account
find operation that looking for word on website
